### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by dansou901** [alanfranz/docker-rpm-builder#19] opened 2016-03-09 14:44 UTC
Hi,
do you plan to do a PKGBUILD for the Arch Linux AUR? If not, I'll just compile from source. Maybe I'll do one myself when I find time.

**Comment by alanfranz** [comment] 2016-03-09 14:48
Hello,
I've got absolutely zero experience with AUR and Arch Linux, and I'm supporting a good number of architectures already :-)

By the way, if you find yourself willing to build, find a place to host, and possibly maintain the Arch version of the package, I'll be happy to review and accept your PRs!

**Comment by dansou901** [comment] 2016-03-09 19:08
Hi,
I just compiled your project from source. What files exactly under devenv after the make get installed by your packages and where? I need to know that for the prefix to use in the PKGBUILD. Thanks!

**Comment by dansou901** [comment] 2016-03-09 19:21
Maybe you could link me your spec file you are using to build your rpms, then I can translate that to PKGBUILD.

**Comment by alanfranz** [comment] 2016-03-09 19:34
Ironically, there's no spec file! I'm using another project of mine to package docker-rpm-builder

https://github.com/alanfranz/fpm-within-docker

The [packaging](https://github.com/alanfranz/docker-rpm-builder/tree/v1dev/packaging) directory contains whatever is needed to build the packages for all the distros I support.

Basically, I use python and virtualenv, creating an environment in a target directory (/opt/docker-rpm-builder), and in such environment I install the source for the software.

Then I symlink the resulting executable (/opt/docker-rpm-builder/devenv/bin/docker-rpmbuilder) to /usr/bin in order to have it in the path.

No, I don't follow FHS or LSB practices, I simply don't care. I think they're cumbersome and outdated.

**Comment by dansou901** [comment] 2016-03-09 19:41
Took a look at that already, seems I'll have to do some of that what fpm is doing myself. Seeing the ready-to-install rpm packages, they install a few symlinks and files which I don't think that they're necessary. So maybe it should work to just move docker-rpm-builder to /usr/bin and that's that. Will report back after trying.

**Comment by alanfranz** [comment] 2016-03-09 20:04
Hello,
I'd better be more precise.

mind you: the docker-rpm-builder directory (/opt/docker-rpm-builder) is a python virtual environment (the same as 'devenv' when developing); the whole directory is needed to run executables in 'bin', because, **intentionally**, docker-rpm-builder is NOT installed as a system-wide python library; it's a separate package with its own deps.

So it won't work if you just move the bin/docker-rpm-builder executable in /usr/bin.

The rpm build is doing very few things:

https://github.com/alanfranz/docker-rpm-builder/blob/v1dev/packaging/centos-7/build-inside/build-package

Just installing everything in /opt/docker-rpm-builder and symlinking (to enable the executable on path). I f you can follow such approach it should be quite fast.

**Comment by dansou901** [comment] 2016-03-09 20:07
Yep, that would be the easiest way. Thanks for the help, that should get me on the way.

**Comment by aframachines** [comment] 2016-03-09 20:08
Thank you for your effort. I hope you succeed.

**Comment by dansou901** [comment] 2016-03-09 21:47
I just did a ready-to-use PKGBUILD. For now it points to my fork of your project. As soon as you merge my pull requst, I can change the source in PKGBUILD to point to your repo again. I'll submit the PKGBUILD to the AUR once the change in source is done. Until then, I'll push it to my github.

**Comment by dansou901** [comment] 2016-03-09 21:52
The PKGBUILD is here: https://github.com/dansou901/docker-rpm-builder-pkgbuild

**Comment by alanfranz** [comment] 2016-03-09 21:54
Your PR was merged.

One small note for PKGBUILD: docker-rpm-builder is Apache Public License 2.0, not GPL3.

**Comment by dansou901** [comment] 2016-03-09 22:08
FIxed, thanks for the hint. Will upload to AUR now. One thing though: As long as the install section is only in v1dev, I'm forced to point to v1dev in PKGBUILD. As soon as it gets stable, I can point to v1. I'll do two AUR packages, one for v1dev branch and one for v1.

**Comment by dansou901** [comment] 2016-03-09 23:42
I had to remove the PKGBUILD from the AUR as it just won't work the way I thought it would work. That one will be a bit more complicated. Can you make your setup.py in a way that is installable like described here (https://wiki.archlinux.org/index.php/Python_package_guidelines, example can be found here: https://projects.archlinux.org/abs.git/tree/prototypes/PKGBUILD-python.proto). Then I can create a working PKGBUILD. Otherwise, the virtualenv gets messed up completely. It worked before because I didn't delete my build directories, which was a mistake.

**Comment by alanfranz** [comment] 2016-03-10 12:56
Hello dansou901,
having worked a lot with packaging on various distros, and with python packaging as well - I'll tell you that's the wrong way to do it.

docker-rpm-builder is an application, not a library. The fact that it's written in python is a detail. How would you package a different application? Then, if you install it systemwide, you are tied to systemwide deps.

The problem with virtualenv is that they memorize the paths in the shebang. You can try with `--relocatable` after you've created the virtualenv.

**Comment by dansou901** [comment] 2016-03-10 13:14
I tried with --relocatable already, but that didn't work. Seems like it's not possible to do a PKGBUILD for the AUR for this software then, so I'll just use it as provided from source.

**Comment by dansou901** [comment] 2016-03-10 13:25
If I try to do --relocatable and move the devenv folder somewhere else, I get

``` ruby
Traceback (most recent call last):
  File "./docker-rpm-builder", line 8, in <module>
    from pkg_resources import load_entry_point
  File "/opt/devenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/opt/devenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/opt/devenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/devenv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: docker-rpm-builder==0.99.dev0
```

**Comment by alanfranz** [comment] 2016-03-10 13:41
Packaging is always an hard problem, but it's usually solvable. One of the things I like in docker-rpm-builder is that I can use the "real" target path, then move it. By the way, I think your doing it wrong. About virtualenv: I think you aren't using it properly; I had doubts about your "install" target -why would you require it in my makefile, when you could write anything in your package() func?

You should create the virtualenv, install docker-rpm-builder inside it, then call relocatable on the whole environment:

```
alan@afralatitude:~/sources/docker-rpm-builder$ virtualenv -p /usr/bin/python2.7 /tmp/something
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /tmp/something/bin/python2.7
Also creating executable in /tmp/something/bin/python
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py:25: UserWarning: SubjectAltName support is disabled - check pyasn1 package installation to enable
  warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
Installing setuptools, pip, wheel...done.
alan@afralatitude:~/sources/docker-rpm-builder$ /tmp/something/bin/pip install .
Processing /home/alan/sources/docker-rpm-builder
Collecting Click==6.2 (from docker-rpm-builder==0.99.dev0)
/tmp/something/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/tmp/something/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached click-6.2-py2.py3-none-any.whl
Collecting unittest2==0.8.0 (from docker-rpm-builder==0.99.dev0)
  Using cached unittest2-0.8.0-py2.py3-none-any.whl
Collecting setuptools==12.0.5 (from docker-rpm-builder==0.99.dev0)
  Using cached setuptools-12.0.5-py2.py3-none-any.whl
Collecting tzlocal==1.2 (from docker-rpm-builder==0.99.dev0)
Collecting pytz==2015.7 (from docker-rpm-builder==0.99.dev0)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from unittest2==0.8.0->docker-rpm-builder==0.99.dev0)
Collecting six (from unittest2==0.8.0->docker-rpm-builder==0.99.dev0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: docker-rpm-builder
  Running setup.py bdist_wheel for docker-rpm-builder ... done
  Stored in directory: /home/alan/.cache/pip/wheels/62/36/b8/75652893c86b627e2aaf259ad07e88efe59379c895c89e42bb
Successfully built docker-rpm-builder
Installing collected packages: Click, six, unittest2, setuptools, pytz, tzlocal, docker-rpm-builder
  Found existing installation: setuptools 20.2.2
    Uninstalling setuptools-20.2.2:
      Successfully uninstalled setuptools-20.2.2
Successfully installed Click-6.2 docker-rpm-builder-0.99.dev0 pytz-2015.7 setuptools-12.0.5 six-1.10.0 tzlocal-1.2 unittest2-0.8.0
alan@afralatitude:~/sources/docker-rpm-builder$ virtualenv --relocatable /tmp/something
Making script /tmp/something/bin/wheel relative
Making script /tmp/something/bin/python-config relative
Making script /tmp/something/bin/easy_install-2.7 relative
Making script /tmp/something/bin/docker-rpm-builder relative
Making script /tmp/something/bin/pip2 relative
Making script /tmp/something/bin/pip2.7 relative
Making script /tmp/something/bin/pip relative
Making script /tmp/something/bin/easy_install relative
Making script /tmp/something/bin/unit2 relative
alan@afralatitude:~/sources/docker-rpm-builder$ cd /tmp/
alan@afralatitude:/tmp$ mv something else
alan@afralatitude:/tmp$ else/bin/docker-rpm-builder 
Usage: docker-rpm-builder [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  dir       Builds a binary RPM from a directory.
  genspec   Generates a spec file from a spectemplate.
  selftest  Perform a selftest.
  srcrpm    Builds a binary RPM from .src.rpm file.
alan@afralatitude:/tmp$ 
```

In PKGBUILD context, as far as I can understand, the best thing to do would be:
- follow the steps in any of the packaging build-inside scripts - that is, install everything in /opt/docker-rpm-builder (i hope the root fs is not readonly in PKGBUILD)
- THEN move /opt to ${pkgdir}
- THEN move to ${pkgdir}/usr/bin and create a RELATIVE symlink to ../../opt/docker-rpm-builder/bin/docker-rpm-builder

if you'd like to experiment I suggest you go on with your fork, rather than upstream source; it would be easier for you.

**Comment by dansou901** [comment] 2016-03-10 14:15
I'll try this evening on my arch machine, haven't got one at work right now. For the first step: PKGBUILD requires to install everything in a subdirectory of $pkgdir and never use root fs, because installing in root fs first would meen to install something without letting pacman control it. That could leed to inconsistent systems, especially in rolling release system like Arch.

**Comment by aframachines** [comment] 2016-03-10 14:30
So you cannot write to rootfs? I understand what you said: but if you could
write to rootfs, THEN move, you wouldn't experience the broken paths.

**Comment by dansou901** [comment] 2016-03-10 14:34
That's the point, while building the package I cannot write to root fs, That's why I need --relocatable to function properly.
EDIT: Especially when building from the AUR I cannot write to rootfs, because all packages built via an AUR helper like yaourt are getting built in /tmp/yaourt/$pkgdir and so on. After building and installing the package, the build directory gets deleted automatically.

**Comment by dansou901** [comment] 2016-03-10 21:26
Now I've got it! The new PKGBUILD now doesn't need that install section anymore, so you can remove that again from your Makefile. I used the commands you gave me to construct the build() section and just did a cp -r and an ln -s in the package() section, that worked perfectly then. The package is in the AUR again, name is docker-rpm-builder (to be installed via your favourite AUR helper, I tested successfully with yaourt). I also point to the stable branch now, another package isn't needed for me. If anyone wants, I can do a package for v1dev as well, that's just minor edits. Thanks for your help!

**Comment by dansou901** [comment] 2016-04-07 08:36
As you can see in the comments of my AUR package (https://aur.archlinux.org/packages/docker-rpm-builder), it isn't necessary to build your software in a relocatable virtualenv under /opt, but to do it the way it is suggested there. Do you agree or is there anything in the way? If not, I would change the PKGBUILD accordingly. Thanks again!

**Comment by alanfranz** [comment] 2016-04-07 08:53
Hello Daniel,
what is your request, precisely?

As the package author, I think I have the burden - and the right - to pick my dependencies. I do support my software with such dependencies and with the build system I mandate. Using virtualenv in such fashion makes the system stable and reproducible on most distributions.

I don't agree with distribution-mandated dependencies, because the "dependency matrix" to test everything on multiple distros will just make any software's complexity explode, with very little value for the end user. I've never submitted my RPMs and DEBs upstream because of this exact issue - I want to be solely responsible for my own software.

So: docker-rpm-builder is open source, feel free to do anything you'd like about it in Arch. I think the patches will work - even though removing selftest IMHO is a silly thing (I'd REALLY like to know if the software works where it's installed - how can I differentiate a configuration/system bug from a build bug?) 

Please make sure that bugs from Arch are reported to you (or Arch maintainers), because I won't answer Arch-specific bugs that I cannot reproduce from my latest stable version.

**Comment by alanfranz** [comment] 2016-04-07 09:06
Post scriptum: if you'd like I can add you to my contributors to this repo. Initially not to v1 or v1dev, but we can create a specific Arch branch if you like, so you don't need to maintain patches, and if Arch-related patches are minimal we could merge them to v1dev or v1. And I can turn to you any issue that is opened against Arch :-)

**Comment by dansou901** [comment] 2016-04-07 09:23
Thanks for your comments. I just commented in the AUR and am waiting for a response, after that I'll decide wether to change something or not.

**Comment by alanfranz** [comment] 2016-04-08 10:11
there's one thing the arch maintainer is correct: unittest2 is not useful. i've removed it from my deps.

**Comment by alanfranz** [comment] 2016-05-03 07:40
Hello, feel free to reopen this issue if you'd like to go on with packaging.

**Closed as completed by alanfranz** 2016-05-03 07:40 UTC

**Comment by dansou901** [comment] 2016-05-06 15:47
There is only one thing left: Can you add a note in your docs that an Arch package is availblein the AUR? Just so that people know if they search for it.

**Comment by dansou901** [comment] 2016-11-16 17:40
Just updated the AUR package to 1.32.0. Can you ping me the next time you release a new version so that I can update the AUR package directly? Thanks!
Btw, I still don't see in the docs that there is an Arch Linux package, would be nice!

**Comment by alanfranz** [comment] 2016-11-16 18:02
Yes, I will.

You're right about the docs. But I know nothing about how Arch Linux could be installed. Would you create a pull request for the README? (you can just edit the readme from my repo, github will create the pull request for you).

**Comment by alanfranz** [comment] 2016-11-16 18:03
@dansou901 do you use any rss reader? If you do, just subscribe to https://github.com/alanfranz/docker-rpm-builder/releases.atom and you'll be notified of all new releases.

**Comment by dansou901** [comment] 2016-11-17 20:11
Not for now. If I could subscribe via email, that would help.

**Comment by alanfranz** [comment] 2017-01-06 17:02
A new version is out.

For the future, just watch this project; github will inform you about new releases.
